<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-15T23:43:23 IST" name="Suite" finished-at="2024-02-15T23:44:04 IST" duration-ms="40799">
    <groups>
    </groups>
    <test started-at="2024-02-15T23:43:23 IST" name="FourTest" finished-at="2024-02-15T23:44:04 IST" duration-ms="40799">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:tests.LoginTest@6440112d]" started-at="2024-02-15T23:43:40 IST" name="openBrowser" finished-at="2024-02-15T23:43:48 IST" duration-ms="8204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@6440112d]" started-at="2024-02-15T23:43:48 IST" name="login" data-provider="getLoginData" finished-at="2024-02-15T23:43:53 IST" duration-ms="4992" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc1cdkjein234@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345678]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="clouser()[pri:0, instance:tests.LoginTest@6440112d]" started-at="2024-02-15T23:43:53 IST" name="clouser" finished-at="2024-02-15T23:43:54 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clouser -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.FourTest">
        <test-method signature="testFour()[pri:0, instance:tests.FourTest@795509d9]" started-at="2024-02-15T23:43:23 IST" name="testFour" finished-at="2024-02-15T23:43:35 IST" duration-ms="12114" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.FourTest.testFour(FourTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method is-config="true" signature="close()[pri:0, instance:tests.FourTest@795509d9]" started-at="2024-02-15T23:43:35 IST" name="close" finished-at="2024-02-15T23:43:35 IST" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- tests.FourTest -->
      <class name="tests.ThreeTest">
        <test-method signature="testThree()[pri:0, instance:tests.ThreeTest@31ea9581]" started-at="2024-02-15T23:43:54 IST" name="testThree" finished-at="2024-02-15T23:44:04 IST" duration-ms="10006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- tests.ThreeTest -->
      <class name="tests.TwoTest">
        <test-method signature="testTwo()[pri:0, instance:tests.TwoTest@5890e879]" started-at="2024-02-15T23:43:35 IST" name="testTwo" finished-at="2024-02-15T23:43:40 IST" duration-ms="4937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- tests.TwoTest -->
    </test> <!-- FourTest -->
  </suite> <!-- Suite -->
</testng-results>
